### index handler

GET http://localhost:8080/

### update handler
PATCH http://localhost:8080/
Content-Type: application/json

{
  "skills": ["Rust", "Go", "TypeScript"]
}

### invalid request

PATCH http://localhost:8081/
Content-Type: application/json

{
  "skills": ["Rust"]
}


### url shortener

POST http://localhost:9876/
Content-Type: application/json

{
  "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422"
}

### url redirect

GET http://localhost:9876/wlGl3G
