### index handler

GET http://localhost:8080/

### update handler
PATCH http://localhost:8080/
Content-Type: application/json

{
  "skills": ["Rust", "Go", "TypeScript"]
}

### invalid request

PATCH http://localhost:8081/
Content-Type: application/json

{
  "skills": ["Rust"]
}
